server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://http://192.168.99.100:5432/webflux
    username: postgres
    password: goryacms
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    sql-script-encoding: UTF-8
    initialization-mode: always
#    maximum-pool-size: 15

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true #fix hibernate not correctly handling available features