server:
  port: 8888

spring:
  datasource:
    url: jdbc:h2:mem:practice_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
    platform: h2
    sql-script-encoding: UTF-8
    initialization-mode: always
#    maximum-pool-size: 15

    # enable H2 web console and set url for web console
    # http://localhost:8888/console
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true #fix hibernate not correctly handling available features